### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by linakherchi** [MichaelClaytonNoble/Eventlite#3]
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [ ] Correctly formatted
    - [x] schema is written in a table format
    - [ ] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [ ] columns names are lowercased and snaked_cased and `back_ticked`

**Comment by linakherchi** [comment]
Thanks, Michael ! 

You might want to remove the ticket_id foreign_key from the events table. You might instead want to add a column that holds the number of tickets available.

I really like that you created a separate table for your event details but I still feel it would be better to have all of the columns inside of your event details moved to your events table. Even though that might feel overwhelming, it will lead to faster retrieval of your event data.

Regarding your tickets table, you might want to remove the quantity (Every time a user buys a ticket, a new row would be added in that tickets table; If a user ends up buying 3 tickets, you would then add 3 rows in that tickets table. You would need to update the quantity of available tickets in the events table according to each user purchase).

Finally, please update how your schema is displayed according to the checklist above. 

You might need to update your state according to the changes I suggested for your schema so I might check that after you make the necessary updates and reassign this issue back to me. 

Let me know if you have questions

**Comment by linakherchi** [comment]
Looking better ! Please fix the format.

**Comment by makonobo** [comment]
> Looking better ! Please fix the format.

**Comment by MichaelClaytonNoble** [comment]
Lina,

Would you mind checking the updates I have made to the schema? 
I added in a locations table. The event must be in one of those locations. Only of the three columns Venue, TBA, or Online can be selected at once. My thought process is create a table which holds these values and the events will contain a foreign key that links to them. 
I would like to know what you think about this design feature and also the 'has one' relationships in my shcema. 
`events` has one `categories`
`events` has one `locations`

Let me know what you think.

**Comment by linakherchi** [comment]
Hi Michael ! 

Thanks. You do not need a locations table. Instead, you can have one location column in your events and create a validation for that column that checks for inclusion, as so:

```validates :location, inclusion: { in: ["Venue, "TBA", "Online"] }```


Regarding the connection between your events and categories, if you want your event to only belong to one category, you can remove the `event_categories` tables and add a foreign key `category_id` in your events table.
The way you currently have it set up is such that events can have multiple categories.
