### ISSUE TITLE
Frontend Routes

### ISSUE THREAD

**Issue by linakherchi** [MichaelClaytonNoble/Eventlite#6]
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

**Comment by linakherchi** [comment]
Thanks, Michael ! 

What is the difference between the frontend routes below ? 

/signin
/signin/signup
/signin/login


Also, if you are going to allow the creation of an event by entering only basic information, and then allow to add details to that event, you will need to remove all not-null constraints related to even detail columns in your schema.

Let me know !

**Comment by MichaelClaytonNoble** [comment]
`/signin` ---> allows the user to enter in an email address 

after clicking a button called "Get Started" 

the user is routed to one of two pages

1. `/signin/signup` if the email address does not exist in the database 
- the user can enter in information about themselves --name, email and password 

or
1. `/signin/login` if the user's email exists within the database. 
- the user can enter in their password along with their email and log in.
